# Generated by Django 4.0 on 2022-01-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('uid', models.IntegerField(max_length=10000)),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('pokemonType', models.CharField(max_length=100)),
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
