# Generated by Django 4.0 on 2022-01-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colorEnglish', '0002_gamecontentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameControlModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
