# Generated by Django 4.0 on 2022-01-15 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colorEnglish', '0003_gamecontrolmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameControlModel',
        ),
    ]
