# Generated by Django 4.0 on 2022-01-24 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineQuerySystem', '0002_alter_question_inputtext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='acccount',
            new_name='account',
        ),
    ]
