# Generated by Django 4.0 on 2022-01-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileNameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1000)),
                ('fileName', models.CharField(max_length=100)),
                ('displaySetting', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FilePathModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(auto_now=True)),
                ('displaySetting', models.IntegerField()),
            ],
        ),
    ]
